name: Generate API documentation

on: 
  push:
    branches:
      - main

jobs:
  generate-docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
    
      - name: Generate documentation
        run: .github/generate-docs.sh
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          TECHNICAL_USER_TOKEN: ${{ secrets.TECHNICAL_USER_TOKEN }}
          TECHNICAL_USER: ${{ secrets.TECHNICAL_USER }}